version: 2

# Build configuration
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  apt_packages:
    - build-essential
  commands:
    - pip install -r requirements.txt
    - pip install .

sphinx:
  builder: html
  configuration: doc/conf.py
