name: Build and Upload Python Package

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        wheel-platform: [manylinux1_x86_64, manylinux2014_x86_64, win_amd64, macosx_10_9_x86_64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install twine

      - name: Build and package
        run: |
          python setup.py sdist bdist_wheel

      - name: Auditwheel
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          docker run --rm -v "$(pwd):/io" -w /io quay.io/pypa/manylinux2014_x86_64 /io/.github/workflows/auditwheel.sh

      - name: Upload to PyPI
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v2
        with:
          username: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository-url: https://upload.pypi.org/legacy/
          distribution: "dist/*"
